# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordsConverter
                                 A QGIS plugin
 This Plugin convert coordinates from dms and dm to utm
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-21
        copyright            : (C) 2021 by Ahmed Abdelkarim
        email                : a.abdelkarim9696@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordsConverter class from file CoordsConverter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coords_converter import CoordsConverter
    return CoordsConverter(iface)
