# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ahmed\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\coords_converter\coords_converter_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoordsConverterDialogBase(object):
    def setupUi(self, CoordsConverterDialogBase):
        CoordsConverterDialogBase.setObjectName("CoordsConverterDialogBase")
        CoordsConverterDialogBase.resize(734, 328)
        CoordsConverterDialogBase.setMinimumSize(QtCore.QSize(734, 328))
        CoordsConverterDialogBase.setMaximumSize(QtCore.QSize(734, 328))
        CoordsConverterDialogBase.setStyleSheet("QWidget#frmLogin,QWidget#frmPopup,QWidget#frmHostInfo,QWidget#frmLogout,QWidget#frmConfig,QWidget#frmData,QWidget#frmDefence,QWidget#frmHost,QWidget#frmMain,QWidget#frmPwd,QWidget#frmSelect,QWidget#frmMessageBox{\n"
"    border:1px solid #1B89CA;\n"
"    border-radius:0px;    \n"
"}\n"
"\n"
".QFrame{\n"
"    border:1px solid #5CACEE;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QWidget#widget_title{\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5);\n"
"}\n"
"\n"
"QLabel#lab_Ico,QLabel#lab_Title{\n"
"    border-radius:0px;\n"
"    color: #F0F0F0;\n"
"    background-color:rgba(0,0,0,0);\n"
"    border-style:none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #5CACEE;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background: none;\n"
"    selection-background-color: #1B89CA;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { \n"
"    lineedit-password-character: 9679; \n"
"}\n"
"\n"
".QGroupBox{\n"
"    border: 1px solid #5CACEE;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton{\n"
"    border-style: none;\n"
"    border: 0px;\n"
"    color: #F0F0F0;\n"
"    padding: 5px;    \n"
"    min-height: 20px;\n"
"    border-radius:5px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
".QPushButton[focusPolicy=\"0\"] {\n"
"    border-style: none;\n"
"    border: 0px;\n"
"    color: #F0F0F0;\n"
"    padding: 0px;    \n"
"    min-height: 10px;\n"
"    border-radius:3px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
".QPushButton:hover{ \n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD);\n"
"}\n"
"\n"
".QPushButton:pressed{ \n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5);\n"
"}\n"
"\n"
"QPushButton#btnMenu,QPushButton#btnMenu_Min,QPushButton#btnMenu_Max,QPushButton#btnMenu_Close{\n"
"    border-radius:0px;\n"
"    color: #F0F0F0;\n"
"    background-color:rgba(0,0,0,0);\n"
"    border-style:none;\n"
"}\n"
"\n"
"QPushButton#btnMenu:hover,QPushButton#btnMenu_Min:hover,QPushButton#btnMenu_Max:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(25, 134, 199, 0), stop:1 #5CACEE);\n"
"}\n"
"\n"
"QPushButton#btnMenu_Close:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(238, 0, 0, 128), stop:1 rgba(238, 44, 44, 255));\n"
"}\n"
"\n"
"QCheckBox {\n"
"    spacing: 2px; \n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/qss_icons/img_rc/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/qss_icons/img_rc/checkbox_checked.png); \n"
"}\n"
"\n"
"QRadioButton {\n"
"    spacing: 2px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px; \n"
"    height: 15px; \n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    image: url(:/qss_icons/img_rc/radio_normal.png); \n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    image: url(:/qss_icons/img_rc/radio_selected.png); \n"
"}\n"
"\n"
"QComboBox,QDateEdit{\n"
"    border-radius: 3px;\n"
"    padding: 1px 10px 1px 5px;\n"
"    border: 1px solid #5CACEE;\n"
"}\n"
"\n"
"QComboBox::drop-down,QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px; \n"
"    border-left-width: 1px;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border-left-color: #5CACEE;\n"
"}\n"
"\n"
"QComboBox::down-arrow,QDateEdit::down-arrow {\n"
"    image: url(:/qss_icons/img_rc/array_down.png); \n"
"}\n"
"\n"
"QMenu {\n"
"    background-color:#F0F0F0;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::item {    \n"
"    padding: 2px 12px 2px 12px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    color: #FFFFFF;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #5CACEE;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    border: 1px solid #5CACEE;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    width: 5px; \n"
"    margin: 0.5px;\n"
"    background-color: #1B89CA;\n"
"}\n"
"\n"
"QSlider::groove:horizontal,QSlider::add-page:horizontal { \n"
"    background: #808080; \n"
"    height: 8px; \n"
"    border-radius: 3px; \n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    height: 8px; \n"
"    border-radius: 3px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 13px; \n"
"    margin-top: -3px; \n"
"    margin-bottom: -3px; \n"
"    border-radius: 6px;\n"
"    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,stop:0.6 #F0F0F0, stop:0.778409 #5CACEE);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0,stop:0.778409 #1B89CA);\n"
"}\n"
"\n"
"QSlider::groove:vertical,QSlider::sub-page:vertical {\n"
"    background:#808080; \n"
"    width: 8px; \n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    width: 8px;\n"
"    border-radius: 3px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 14px; \n"
"    margin-left: -3px;\n"
"    margin-right: -3px;\n"
"    border-radius: 6px;\n"
"    background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0, stop:0.778409 #5CACEE);\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0,stop:0.778409 #1B89CA);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width:10px; \n"
"    background-color:rgba(0,0,0,0%); \n"
"    padding-top:10px; \n"
"    padding-bottom:10px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height:10px; \n"
"    background-color:rgba(0,0,0,0%); \n"
"    padding-left:10px; padding-right:10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    width:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    height:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    width:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    height:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: bottom; \n"
"    subcontrol-origin: margin;\n"
"    border-image:url(:/qss_icons/img_rc/add-line_vertical.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"    border-image:url(:/qss_icons/img_rc/add-line_horizontal.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: top; \n"
"    subcontrol-origin: margin;\n"
"    border-image:url(:/qss_icons/img_rc/sub-line_vertical.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"    border-image:url(:/qss_icons/img_rc/sub-line_horizontal.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical {\n"
"    width:10px;\n"
"    background: #C0C0C0;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal {\n"
"    height:10px;\n"
"    background: #C0C0C0;\n"
"}\n"
"\n"
"QScrollArea {\n"
"    border: 0px ; \n"
"}\n"
"\n"
"QTreeView,QListView,QTableView{\n"
"    border: 1px solid #5CACEE; \n"
"    selection-background-color: #1B89CA;\n"
"    selection-color: #F0F0F0;\n"
"}\n"
"\n"
"QTableView::item:selected, QListView::item:selected, QTreeView::item:selected {\n"
"    color: #F0F0F0;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QTableView::item:hover, QListView::item:hover, QTreeView::item:hover {\n"
"    color: #F0F0F0;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QTableView::item, QListView::item, QTreeView::item {\n"
"    padding: 5px; \n"
"    margin: 0px; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    padding:3px;\n"
"    margin:0px;\n"
"    color:#F0F0F0;\n"
"    border: 1px solid #F0F0F0;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom-left-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"    color: #F0F0F0;\n"
"    min-width: 60px;\n"
"    min-height: 20px;\n"
"    padding: 3px 8px 3px 8px;\n"
"    margin:1px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QStatusBar::item {\n"
"     border: 1px solid #5CACEE;\n"
"     border-radius: 3px;\n"
"}")
        self.tabWidget = QtWidgets.QTabWidget(CoordsConverterDialogBase)
        self.tabWidget.setGeometry(QtCore.QRect(180, 10, 541, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(30, 110, 171, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 170, 201, 20))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 250, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(300, 70, 51, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 110, 201, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(90, 70, 51, 20))
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 170, 171, 20))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setGeometry(QtCore.QRect(440, 170, 41, 20))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setGeometry(QtCore.QRect(490, 170, 41, 20))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(90, 140, 61, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(300, 140, 61, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(446, 150, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(496, 150, 31, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 250, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(200, 20, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(340, 70, 51, 20))
        self.label_25.setObjectName("label_25")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_25.setGeometry(QtCore.QRect(40, 100, 201, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_26 = QtWidgets.QLabel(self.tab_3)
        self.label_26.setGeometry(QtCore.QRect(110, 70, 51, 20))
        self.label_26.setObjectName("label_26")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_26.setGeometry(QtCore.QRect(260, 100, 211, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_27.setGeometry(QtCore.QRect(62, 180, 40, 20))
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_28.setGeometry(QtCore.QRect(122, 180, 40, 20))
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_29.setGeometry(QtCore.QRect(182, 180, 50, 20))
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_30.setGeometry(QtCore.QRect(350, 180, 40, 20))
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_31.setGeometry(QtCore.QRect(290, 180, 40, 20))
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_32.setGeometry(QtCore.QRect(410, 180, 50, 20))
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(110, 140, 51, 20))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(340, 140, 51, 20))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setGeometry(QtCore.QRect(74, 157, 16, 20))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setGeometry(QtCore.QRect(134, 158, 16, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(200, 158, 16, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(305, 159, 16, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setGeometry(QtCore.QRect(366, 160, 16, 20))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setGeometry(QtCore.QRect(432, 160, 16, 20))
        self.label_34.setObjectName("label_34")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setGeometry(QtCore.QRect(450, 250, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(360, 250, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(150, 20, 231, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(491, 90, 20, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(290, 80, 61, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(210, 180, 191, 20))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 250, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(438, 90, 20, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 250, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setGeometry(QtCore.QRect(20, 110, 171, 20))
        self.lineEdit_9.setReadOnly(False)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(20, 180, 171, 20))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_12.setEnabled(True)
        self.lineEdit_12.setGeometry(QtCore.QRect(210, 110, 191, 20))
        self.lineEdit_12.setReadOnly(False)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(80, 80, 61, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(290, 150, 51, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(80, 150, 51, 20))
        self.label_12.setObjectName("label_12")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(200, 20, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(423, 110, 50, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(477, 110, 50, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_33.setEnabled(True)
        self.lineEdit_33.setGeometry(QtCore.QRect(14, 110, 191, 20))
        self.lineEdit_33.setReadOnly(False)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_34.setEnabled(True)
        self.lineEdit_34.setGeometry(QtCore.QRect(234, 110, 181, 20))
        self.lineEdit_34.setReadOnly(False)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.label_35 = QtWidgets.QLabel(self.tab_7)
        self.label_35.setGeometry(QtCore.QRect(300, 80, 61, 21))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setGeometry(QtCore.QRect(491, 90, 31, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_7)
        self.label_37.setGeometry(QtCore.QRect(90, 80, 61, 21))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_7)
        self.label_38.setGeometry(QtCore.QRect(435, 90, 31, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_7)
        self.label_39.setGeometry(QtCore.QRect(34, 167, 16, 20))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(388, 170, 16, 20))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_7)
        self.label_41.setGeometry(QtCore.QRect(300, 150, 51, 20))
        self.label_41.setObjectName("label_41")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_37.setGeometry(QtCore.QRect(82, 190, 40, 20))
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_38.setGeometry(QtCore.QRect(22, 190, 40, 20))
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.label_42 = QtWidgets.QLabel(self.tab_7)
        self.label_42.setGeometry(QtCore.QRect(94, 168, 16, 20))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab_7)
        self.label_43.setGeometry(QtCore.QRect(261, 169, 16, 20))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_7)
        self.label_44.setGeometry(QtCore.QRect(321, 170, 16, 20))
        self.label_44.setObjectName("label_44")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_39.setGeometry(QtCore.QRect(310, 190, 40, 20))
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.label_45 = QtWidgets.QLabel(self.tab_7)
        self.label_45.setGeometry(QtCore.QRect(70, 150, 51, 20))
        self.label_45.setObjectName("label_45")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_40.setGeometry(QtCore.QRect(142, 190, 50, 20))
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_46 = QtWidgets.QLabel(self.tab_7)
        self.label_46.setGeometry(QtCore.QRect(160, 168, 16, 20))
        self.label_46.setObjectName("label_46")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_41.setGeometry(QtCore.QRect(250, 190, 40, 20))
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_42.setGeometry(QtCore.QRect(370, 190, 50, 20))
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_15.setGeometry(QtCore.QRect(360, 250, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_16.setGeometry(QtCore.QRect(450, 250, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setGeometry(QtCore.QRect(170, 20, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_3.setGeometry(QtCore.QRect(476, 110, 51, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_4.setGeometry(QtCore.QRect(420, 110, 51, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_47 = QtWidgets.QLabel(self.tab_8)
        self.label_47.setGeometry(QtCore.QRect(273, 99, 16, 20))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_8)
        self.label_48.setGeometry(QtCore.QRect(46, 97, 16, 20))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_8)
        self.label_49.setGeometry(QtCore.QRect(333, 100, 16, 20))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_8)
        self.label_50.setGeometry(QtCore.QRect(82, 80, 51, 20))
        self.label_50.setObjectName("label_50")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_43.setGeometry(QtCore.QRect(322, 120, 40, 20))
        self.lineEdit_43.setReadOnly(False)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_44.setGeometry(QtCore.QRect(382, 120, 50, 20))
        self.lineEdit_44.setReadOnly(False)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_45.setGeometry(QtCore.QRect(94, 120, 40, 20))
        self.lineEdit_45.setReadOnly(False)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_46.setGeometry(QtCore.QRect(262, 120, 40, 20))
        self.lineEdit_46.setReadOnly(False)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.label_51 = QtWidgets.QLabel(self.tab_8)
        self.label_51.setGeometry(QtCore.QRect(106, 98, 16, 20))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_8)
        self.label_52.setGeometry(QtCore.QRect(400, 100, 16, 20))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_8)
        self.label_53.setGeometry(QtCore.QRect(312, 80, 51, 20))
        self.label_53.setObjectName("label_53")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_47.setGeometry(QtCore.QRect(34, 120, 40, 20))
        self.lineEdit_47.setReadOnly(False)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.label_54 = QtWidgets.QLabel(self.tab_8)
        self.label_54.setGeometry(QtCore.QRect(172, 98, 16, 20))
        self.label_54.setObjectName("label_54")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_48.setGeometry(QtCore.QRect(154, 120, 50, 20))
        self.lineEdit_48.setReadOnly(False)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_49.setEnabled(True)
        self.lineEdit_49.setGeometry(QtCore.QRect(434, 190, 41, 20))
        self.lineEdit_49.setReadOnly(True)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_50.setEnabled(True)
        self.lineEdit_50.setGeometry(QtCore.QRect(24, 190, 191, 20))
        self.lineEdit_50.setReadOnly(True)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_51.setEnabled(True)
        self.lineEdit_51.setGeometry(QtCore.QRect(484, 190, 41, 20))
        self.lineEdit_51.setReadOnly(True)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.label_55 = QtWidgets.QLabel(self.tab_8)
        self.label_55.setGeometry(QtCore.QRect(490, 170, 31, 16))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_8)
        self.label_56.setGeometry(QtCore.QRect(310, 160, 61, 21))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_8)
        self.label_57.setGeometry(QtCore.QRect(440, 170, 31, 16))
        self.label_57.setObjectName("label_57")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_52.setEnabled(True)
        self.lineEdit_52.setGeometry(QtCore.QRect(244, 190, 181, 20))
        self.lineEdit_52.setReadOnly(True)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.label_58 = QtWidgets.QLabel(self.tab_8)
        self.label_58.setGeometry(QtCore.QRect(100, 160, 61, 21))
        self.label_58.setObjectName("label_58")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_25.setGeometry(QtCore.QRect(360, 250, 75, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_26.setGeometry(QtCore.QRect(450, 250, 75, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_19 = QtWidgets.QLabel(self.tab_8)
        self.label_19.setGeometry(QtCore.QRect(170, 20, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.label_105 = QtWidgets.QLabel(self.tab_14)
        self.label_105.setGeometry(QtCore.QRect(133, 108, 16, 20))
        self.label_105.setObjectName("label_105")
        self.lineEdit_93 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_93.setGeometry(QtCore.QRect(39, 200, 201, 20))
        self.lineEdit_93.setReadOnly(True)
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.lineEdit_94 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_94.setGeometry(QtCore.QRect(259, 200, 211, 20))
        self.lineEdit_94.setReadOnly(True)
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.label_106 = QtWidgets.QLabel(self.tab_14)
        self.label_106.setGeometry(QtCore.QRect(109, 170, 51, 20))
        self.label_106.setObjectName("label_106")
        self.lineEdit_95 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_95.setGeometry(QtCore.QRect(61, 130, 40, 20))
        self.lineEdit_95.setReadOnly(False)
        self.lineEdit_95.setObjectName("lineEdit_95")
        self.lineEdit_96 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_96.setGeometry(QtCore.QRect(349, 130, 40, 20))
        self.lineEdit_96.setReadOnly(False)
        self.lineEdit_96.setObjectName("lineEdit_96")
        self.lineEdit_97 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_97.setGeometry(QtCore.QRect(181, 130, 50, 20))
        self.lineEdit_97.setReadOnly(False)
        self.lineEdit_97.setObjectName("lineEdit_97")
        self.label_107 = QtWidgets.QLabel(self.tab_14)
        self.label_107.setGeometry(QtCore.QRect(300, 109, 16, 20))
        self.label_107.setObjectName("label_107")
        self.lineEdit_98 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_98.setGeometry(QtCore.QRect(289, 130, 40, 20))
        self.lineEdit_98.setReadOnly(False)
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.label_108 = QtWidgets.QLabel(self.tab_14)
        self.label_108.setGeometry(QtCore.QRect(199, 108, 16, 20))
        self.label_108.setObjectName("label_108")
        self.lineEdit_99 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_99.setGeometry(QtCore.QRect(121, 130, 40, 20))
        self.lineEdit_99.setReadOnly(False)
        self.lineEdit_99.setObjectName("lineEdit_99")
        self.lineEdit_100 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_100.setGeometry(QtCore.QRect(409, 130, 50, 20))
        self.lineEdit_100.setReadOnly(False)
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.label_109 = QtWidgets.QLabel(self.tab_14)
        self.label_109.setGeometry(QtCore.QRect(109, 90, 51, 20))
        self.label_109.setObjectName("label_109")
        self.label_110 = QtWidgets.QLabel(self.tab_14)
        self.label_110.setGeometry(QtCore.QRect(427, 110, 16, 20))
        self.label_110.setObjectName("label_110")
        self.label_111 = QtWidgets.QLabel(self.tab_14)
        self.label_111.setGeometry(QtCore.QRect(73, 107, 16, 20))
        self.label_111.setObjectName("label_111")
        self.label_112 = QtWidgets.QLabel(self.tab_14)
        self.label_112.setGeometry(QtCore.QRect(339, 90, 51, 20))
        self.label_112.setObjectName("label_112")
        self.label_113 = QtWidgets.QLabel(self.tab_14)
        self.label_113.setGeometry(QtCore.QRect(339, 170, 51, 20))
        self.label_113.setObjectName("label_113")
        self.label_114 = QtWidgets.QLabel(self.tab_14)
        self.label_114.setGeometry(QtCore.QRect(360, 110, 16, 20))
        self.label_114.setObjectName("label_114")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_27.setGeometry(QtCore.QRect(360, 250, 75, 23))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_28.setGeometry(QtCore.QRect(450, 250, 75, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.label_20 = QtWidgets.QLabel(self.tab_14)
        self.label_20.setGeometry(QtCore.QRect(150, 20, 231, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.tab_14, "")
        self.groupBox = QtWidgets.QGroupBox(CoordsConverterDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(-11, -30, 181, 391))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 55, 171, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(10, 102, 171, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(10, 149, 171, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(10, 196, 171, 41))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_5.setGeometry(QtCore.QRect(10, 243, 171, 41))
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        self.commandLinkButton_6 = QtWidgets.QCommandLinkButton(self.groupBox)
        self.commandLinkButton_6.setGeometry(QtCore.QRect(10, 290, 171, 41))
        self.commandLinkButton_6.setObjectName("commandLinkButton_6")

        self.retranslateUi(CoordsConverterDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CoordsConverterDialogBase)

    def retranslateUi(self, CoordsConverterDialogBase):
        _translate = QtCore.QCoreApplication.translate
        CoordsConverterDialogBase.setWindowTitle(_translate("CoordsConverterDialogBase", "Coordinates Converter"))
        self.label_13.setText(_translate("CoordsConverterDialogBase", "Welcome to Coordinates Converter Plugin."))
        self.label_14.setText(_translate("CoordsConverterDialogBase", "Please Choose the convert method from the left menu."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("CoordsConverterDialogBase", "home"))
        self.pushButton_5.setText(_translate("CoordsConverterDialogBase", "Convert"))
        self.label_2.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_3.setText(_translate("CoordsConverterDialogBase", "Easting"))
        self.label_4.setText(_translate("CoordsConverterDialogBase", "Northing"))
        self.label_5.setText(_translate("CoordsConverterDialogBase", "Z N"))
        self.label_6.setText(_translate("CoordsConverterDialogBase", "Z L"))
        self.pushButton_6.setText(_translate("CoordsConverterDialogBase", "Clear"))
        self.label_15.setText(_translate("CoordsConverterDialogBase", "Decimal Degree to UTM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CoordsConverterDialogBase", "dm to utm"))
        self.label_25.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label_26.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_27.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_28.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label_29.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_30.setText(_translate("CoordsConverterDialogBase", "M"))
        self.label_31.setText(_translate("CoordsConverterDialogBase", "S"))
        self.label_32.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_33.setText(_translate("CoordsConverterDialogBase", "M"))
        self.label_34.setText(_translate("CoordsConverterDialogBase", "S"))
        self.pushButton_13.setText(_translate("CoordsConverterDialogBase", "Clear"))
        self.pushButton_14.setText(_translate("CoordsConverterDialogBase", "Convert"))
        self.label_16.setText(_translate("CoordsConverterDialogBase", "Decimal Degree to Degree Minut Second"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("CoordsConverterDialogBase", "dm to dms"))
        self.label_7.setText(_translate("CoordsConverterDialogBase", "Z L"))
        self.label_8.setText(_translate("CoordsConverterDialogBase", "Northing"))
        self.pushButton_7.setText(_translate("CoordsConverterDialogBase", "Clear"))
        self.label_9.setText(_translate("CoordsConverterDialogBase", "Z N"))
        self.pushButton_8.setText(_translate("CoordsConverterDialogBase", "Convert"))
        self.label_10.setText(_translate("CoordsConverterDialogBase", "Easting"))
        self.label_11.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label_12.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_17.setText(_translate("CoordsConverterDialogBase", "UTM to Decimal Degree"))
        self.comboBox.setItemText(0, _translate("CoordsConverterDialogBase", "1"))
        self.comboBox.setItemText(1, _translate("CoordsConverterDialogBase", "2"))
        self.comboBox.setItemText(2, _translate("CoordsConverterDialogBase", "3"))
        self.comboBox.setItemText(3, _translate("CoordsConverterDialogBase", "4"))
        self.comboBox.setItemText(4, _translate("CoordsConverterDialogBase", "5"))
        self.comboBox.setItemText(5, _translate("CoordsConverterDialogBase", "6"))
        self.comboBox.setItemText(6, _translate("CoordsConverterDialogBase", "7"))
        self.comboBox.setItemText(7, _translate("CoordsConverterDialogBase", "8"))
        self.comboBox.setItemText(8, _translate("CoordsConverterDialogBase", "9"))
        self.comboBox.setItemText(9, _translate("CoordsConverterDialogBase", "10"))
        self.comboBox.setItemText(10, _translate("CoordsConverterDialogBase", "11"))
        self.comboBox.setItemText(11, _translate("CoordsConverterDialogBase", "12"))
        self.comboBox.setItemText(12, _translate("CoordsConverterDialogBase", "13"))
        self.comboBox.setItemText(13, _translate("CoordsConverterDialogBase", "14"))
        self.comboBox.setItemText(14, _translate("CoordsConverterDialogBase", "15"))
        self.comboBox.setItemText(15, _translate("CoordsConverterDialogBase", "16"))
        self.comboBox.setItemText(16, _translate("CoordsConverterDialogBase", "17"))
        self.comboBox.setItemText(17, _translate("CoordsConverterDialogBase", "18"))
        self.comboBox.setItemText(18, _translate("CoordsConverterDialogBase", "19"))
        self.comboBox.setItemText(19, _translate("CoordsConverterDialogBase", "20"))
        self.comboBox.setItemText(20, _translate("CoordsConverterDialogBase", "21"))
        self.comboBox.setItemText(21, _translate("CoordsConverterDialogBase", "22"))
        self.comboBox.setItemText(22, _translate("CoordsConverterDialogBase", "23"))
        self.comboBox.setItemText(23, _translate("CoordsConverterDialogBase", "24"))
        self.comboBox.setItemText(24, _translate("CoordsConverterDialogBase", "25"))
        self.comboBox.setItemText(25, _translate("CoordsConverterDialogBase", "26"))
        self.comboBox.setItemText(26, _translate("CoordsConverterDialogBase", "27"))
        self.comboBox.setItemText(27, _translate("CoordsConverterDialogBase", "28"))
        self.comboBox.setItemText(28, _translate("CoordsConverterDialogBase", "29"))
        self.comboBox.setItemText(29, _translate("CoordsConverterDialogBase", "30"))
        self.comboBox.setItemText(30, _translate("CoordsConverterDialogBase", "31"))
        self.comboBox.setItemText(31, _translate("CoordsConverterDialogBase", "32"))
        self.comboBox.setItemText(32, _translate("CoordsConverterDialogBase", "33"))
        self.comboBox.setItemText(33, _translate("CoordsConverterDialogBase", "34"))
        self.comboBox.setItemText(34, _translate("CoordsConverterDialogBase", "35"))
        self.comboBox.setItemText(35, _translate("CoordsConverterDialogBase", "36"))
        self.comboBox.setItemText(36, _translate("CoordsConverterDialogBase", "37"))
        self.comboBox.setItemText(37, _translate("CoordsConverterDialogBase", "38"))
        self.comboBox.setItemText(38, _translate("CoordsConverterDialogBase", "39"))
        self.comboBox.setItemText(39, _translate("CoordsConverterDialogBase", "40"))
        self.comboBox.setItemText(40, _translate("CoordsConverterDialogBase", "41"))
        self.comboBox.setItemText(41, _translate("CoordsConverterDialogBase", "42"))
        self.comboBox.setItemText(42, _translate("CoordsConverterDialogBase", "43"))
        self.comboBox.setItemText(43, _translate("CoordsConverterDialogBase", "45"))
        self.comboBox.setItemText(44, _translate("CoordsConverterDialogBase", "46"))
        self.comboBox.setItemText(45, _translate("CoordsConverterDialogBase", "47"))
        self.comboBox.setItemText(46, _translate("CoordsConverterDialogBase", "48"))
        self.comboBox.setItemText(47, _translate("CoordsConverterDialogBase", "49"))
        self.comboBox.setItemText(48, _translate("CoordsConverterDialogBase", "50"))
        self.comboBox.setItemText(49, _translate("CoordsConverterDialogBase", "51"))
        self.comboBox.setItemText(50, _translate("CoordsConverterDialogBase", "52"))
        self.comboBox.setItemText(51, _translate("CoordsConverterDialogBase", "53"))
        self.comboBox.setItemText(52, _translate("CoordsConverterDialogBase", "54"))
        self.comboBox.setItemText(53, _translate("CoordsConverterDialogBase", "58"))
        self.comboBox.setItemText(54, _translate("CoordsConverterDialogBase", "59"))
        self.comboBox.setItemText(55, _translate("CoordsConverterDialogBase", "60"))
        self.comboBox_2.setItemText(0, _translate("CoordsConverterDialogBase", "C"))
        self.comboBox_2.setItemText(1, _translate("CoordsConverterDialogBase", "D"))
        self.comboBox_2.setItemText(2, _translate("CoordsConverterDialogBase", "E"))
        self.comboBox_2.setItemText(3, _translate("CoordsConverterDialogBase", "F"))
        self.comboBox_2.setItemText(4, _translate("CoordsConverterDialogBase", "G"))
        self.comboBox_2.setItemText(5, _translate("CoordsConverterDialogBase", "H"))
        self.comboBox_2.setItemText(6, _translate("CoordsConverterDialogBase", "I"))
        self.comboBox_2.setItemText(7, _translate("CoordsConverterDialogBase", "J"))
        self.comboBox_2.setItemText(8, _translate("CoordsConverterDialogBase", "K"))
        self.comboBox_2.setItemText(9, _translate("CoordsConverterDialogBase", "L"))
        self.comboBox_2.setItemText(10, _translate("CoordsConverterDialogBase", "M"))
        self.comboBox_2.setItemText(11, _translate("CoordsConverterDialogBase", "N"))
        self.comboBox_2.setItemText(12, _translate("CoordsConverterDialogBase", "O"))
        self.comboBox_2.setItemText(13, _translate("CoordsConverterDialogBase", "P"))
        self.comboBox_2.setItemText(14, _translate("CoordsConverterDialogBase", "Q"))
        self.comboBox_2.setItemText(15, _translate("CoordsConverterDialogBase", "R"))
        self.comboBox_2.setItemText(16, _translate("CoordsConverterDialogBase", "S"))
        self.comboBox_2.setItemText(17, _translate("CoordsConverterDialogBase", "T"))
        self.comboBox_2.setItemText(18, _translate("CoordsConverterDialogBase", "U"))
        self.comboBox_2.setItemText(19, _translate("CoordsConverterDialogBase", "V"))
        self.comboBox_2.setItemText(20, _translate("CoordsConverterDialogBase", "W"))
        self.comboBox_2.setItemText(21, _translate("CoordsConverterDialogBase", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CoordsConverterDialogBase", "utm to dm"))
        self.label_35.setText(_translate("CoordsConverterDialogBase", "Northing"))
        self.label_36.setText(_translate("CoordsConverterDialogBase", "Z L"))
        self.label_37.setText(_translate("CoordsConverterDialogBase", "Easting"))
        self.label_38.setText(_translate("CoordsConverterDialogBase", "Z N"))
        self.label_39.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_40.setText(_translate("CoordsConverterDialogBase", "S"))
        self.label_41.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label_42.setText(_translate("CoordsConverterDialogBase", "M"))
        self.label_43.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_44.setText(_translate("CoordsConverterDialogBase", "M"))
        self.label_45.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_46.setText(_translate("CoordsConverterDialogBase", "S"))
        self.pushButton_15.setText(_translate("CoordsConverterDialogBase", "Convert"))
        self.pushButton_16.setText(_translate("CoordsConverterDialogBase", "Clear"))
        self.label_18.setText(_translate("CoordsConverterDialogBase", "UTM to Degree Minut Second"))
        self.comboBox_3.setItemText(0, _translate("CoordsConverterDialogBase", "C"))
        self.comboBox_3.setItemText(1, _translate("CoordsConverterDialogBase", "D"))
        self.comboBox_3.setItemText(2, _translate("CoordsConverterDialogBase", "E"))
        self.comboBox_3.setItemText(3, _translate("CoordsConverterDialogBase", "F"))
        self.comboBox_3.setItemText(4, _translate("CoordsConverterDialogBase", "G"))
        self.comboBox_3.setItemText(5, _translate("CoordsConverterDialogBase", "H"))
        self.comboBox_3.setItemText(6, _translate("CoordsConverterDialogBase", "I"))
        self.comboBox_3.setItemText(7, _translate("CoordsConverterDialogBase", "J"))
        self.comboBox_3.setItemText(8, _translate("CoordsConverterDialogBase", "K"))
        self.comboBox_3.setItemText(9, _translate("CoordsConverterDialogBase", "L"))
        self.comboBox_3.setItemText(10, _translate("CoordsConverterDialogBase", "M"))
        self.comboBox_3.setItemText(11, _translate("CoordsConverterDialogBase", "N"))
        self.comboBox_3.setItemText(12, _translate("CoordsConverterDialogBase", "O"))
        self.comboBox_3.setItemText(13, _translate("CoordsConverterDialogBase", "P"))
        self.comboBox_3.setItemText(14, _translate("CoordsConverterDialogBase", "Q"))
        self.comboBox_3.setItemText(15, _translate("CoordsConverterDialogBase", "R"))
        self.comboBox_3.setItemText(16, _translate("CoordsConverterDialogBase", "S"))
        self.comboBox_3.setItemText(17, _translate("CoordsConverterDialogBase", "T"))
        self.comboBox_3.setItemText(18, _translate("CoordsConverterDialogBase", "U"))
        self.comboBox_3.setItemText(19, _translate("CoordsConverterDialogBase", "V"))
        self.comboBox_3.setItemText(20, _translate("CoordsConverterDialogBase", "W"))
        self.comboBox_3.setItemText(21, _translate("CoordsConverterDialogBase", "X"))
        self.comboBox_4.setItemText(0, _translate("CoordsConverterDialogBase", "1"))
        self.comboBox_4.setItemText(1, _translate("CoordsConverterDialogBase", "2"))
        self.comboBox_4.setItemText(2, _translate("CoordsConverterDialogBase", "3"))
        self.comboBox_4.setItemText(3, _translate("CoordsConverterDialogBase", "4"))
        self.comboBox_4.setItemText(4, _translate("CoordsConverterDialogBase", "5"))
        self.comboBox_4.setItemText(5, _translate("CoordsConverterDialogBase", "6"))
        self.comboBox_4.setItemText(6, _translate("CoordsConverterDialogBase", "7"))
        self.comboBox_4.setItemText(7, _translate("CoordsConverterDialogBase", "8"))
        self.comboBox_4.setItemText(8, _translate("CoordsConverterDialogBase", "9"))
        self.comboBox_4.setItemText(9, _translate("CoordsConverterDialogBase", "10"))
        self.comboBox_4.setItemText(10, _translate("CoordsConverterDialogBase", "11"))
        self.comboBox_4.setItemText(11, _translate("CoordsConverterDialogBase", "12"))
        self.comboBox_4.setItemText(12, _translate("CoordsConverterDialogBase", "13"))
        self.comboBox_4.setItemText(13, _translate("CoordsConverterDialogBase", "14"))
        self.comboBox_4.setItemText(14, _translate("CoordsConverterDialogBase", "15"))
        self.comboBox_4.setItemText(15, _translate("CoordsConverterDialogBase", "16"))
        self.comboBox_4.setItemText(16, _translate("CoordsConverterDialogBase", "17"))
        self.comboBox_4.setItemText(17, _translate("CoordsConverterDialogBase", "18"))
        self.comboBox_4.setItemText(18, _translate("CoordsConverterDialogBase", "19"))
        self.comboBox_4.setItemText(19, _translate("CoordsConverterDialogBase", "20"))
        self.comboBox_4.setItemText(20, _translate("CoordsConverterDialogBase", "21"))
        self.comboBox_4.setItemText(21, _translate("CoordsConverterDialogBase", "22"))
        self.comboBox_4.setItemText(22, _translate("CoordsConverterDialogBase", "23"))
        self.comboBox_4.setItemText(23, _translate("CoordsConverterDialogBase", "24"))
        self.comboBox_4.setItemText(24, _translate("CoordsConverterDialogBase", "25"))
        self.comboBox_4.setItemText(25, _translate("CoordsConverterDialogBase", "26"))
        self.comboBox_4.setItemText(26, _translate("CoordsConverterDialogBase", "27"))
        self.comboBox_4.setItemText(27, _translate("CoordsConverterDialogBase", "28"))
        self.comboBox_4.setItemText(28, _translate("CoordsConverterDialogBase", "29"))
        self.comboBox_4.setItemText(29, _translate("CoordsConverterDialogBase", "30"))
        self.comboBox_4.setItemText(30, _translate("CoordsConverterDialogBase", "31"))
        self.comboBox_4.setItemText(31, _translate("CoordsConverterDialogBase", "32"))
        self.comboBox_4.setItemText(32, _translate("CoordsConverterDialogBase", "33"))
        self.comboBox_4.setItemText(33, _translate("CoordsConverterDialogBase", "34"))
        self.comboBox_4.setItemText(34, _translate("CoordsConverterDialogBase", "35"))
        self.comboBox_4.setItemText(35, _translate("CoordsConverterDialogBase", "36"))
        self.comboBox_4.setItemText(36, _translate("CoordsConverterDialogBase", "37"))
        self.comboBox_4.setItemText(37, _translate("CoordsConverterDialogBase", "38"))
        self.comboBox_4.setItemText(38, _translate("CoordsConverterDialogBase", "39"))
        self.comboBox_4.setItemText(39, _translate("CoordsConverterDialogBase", "40"))
        self.comboBox_4.setItemText(40, _translate("CoordsConverterDialogBase", "41"))
        self.comboBox_4.setItemText(41, _translate("CoordsConverterDialogBase", "42"))
        self.comboBox_4.setItemText(42, _translate("CoordsConverterDialogBase", "43"))
        self.comboBox_4.setItemText(43, _translate("CoordsConverterDialogBase", "45"))
        self.comboBox_4.setItemText(44, _translate("CoordsConverterDialogBase", "46"))
        self.comboBox_4.setItemText(45, _translate("CoordsConverterDialogBase", "47"))
        self.comboBox_4.setItemText(46, _translate("CoordsConverterDialogBase", "48"))
        self.comboBox_4.setItemText(47, _translate("CoordsConverterDialogBase", "49"))
        self.comboBox_4.setItemText(48, _translate("CoordsConverterDialogBase", "50"))
        self.comboBox_4.setItemText(49, _translate("CoordsConverterDialogBase", "51"))
        self.comboBox_4.setItemText(50, _translate("CoordsConverterDialogBase", "52"))
        self.comboBox_4.setItemText(51, _translate("CoordsConverterDialogBase", "53"))
        self.comboBox_4.setItemText(52, _translate("CoordsConverterDialogBase", "54"))
        self.comboBox_4.setItemText(53, _translate("CoordsConverterDialogBase", "58"))
        self.comboBox_4.setItemText(54, _translate("CoordsConverterDialogBase", "59"))
        self.comboBox_4.setItemText(55, _translate("CoordsConverterDialogBase", "60"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("CoordsConverterDialogBase", "utm to dms"))
        self.label_47.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_48.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_49.setText(_translate("CoordsConverterDialogBase", "M"))
        self.label_50.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_51.setText(_translate("CoordsConverterDialogBase", "M"))
        self.label_52.setText(_translate("CoordsConverterDialogBase", "S"))
        self.label_53.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label_54.setText(_translate("CoordsConverterDialogBase", "S"))
        self.label_55.setText(_translate("CoordsConverterDialogBase", "Z L"))
        self.label_56.setText(_translate("CoordsConverterDialogBase", "Northing"))
        self.label_57.setText(_translate("CoordsConverterDialogBase", "Z N"))
        self.label_58.setText(_translate("CoordsConverterDialogBase", "Easting"))
        self.pushButton_25.setText(_translate("CoordsConverterDialogBase", "Convert"))
        self.pushButton_26.setText(_translate("CoordsConverterDialogBase", "Clear"))
        self.label_19.setText(_translate("CoordsConverterDialogBase", "Degree Minut Second to UTM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("CoordsConverterDialogBase", "dms to utm"))
        self.label_105.setText(_translate("CoordsConverterDialogBase", "M"))
        self.label_106.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_107.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_108.setText(_translate("CoordsConverterDialogBase", "S"))
        self.label_109.setText(_translate("CoordsConverterDialogBase", "Latitude"))
        self.label_110.setText(_translate("CoordsConverterDialogBase", "S"))
        self.label_111.setText(_translate("CoordsConverterDialogBase", "D"))
        self.label_112.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label_113.setText(_translate("CoordsConverterDialogBase", "Longtude"))
        self.label_114.setText(_translate("CoordsConverterDialogBase", "M"))
        self.pushButton_27.setText(_translate("CoordsConverterDialogBase", "Convert"))
        self.pushButton_28.setText(_translate("CoordsConverterDialogBase", "Clear"))
        self.label_20.setText(_translate("CoordsConverterDialogBase", " Degree Minut Second to Decimal Degree"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("CoordsConverterDialogBase", "dms to dd"))
        self.commandLinkButton.setText(_translate("CoordsConverterDialogBase", "DD to UTM"))
        self.commandLinkButton_2.setText(_translate("CoordsConverterDialogBase", "DD to DMS"))
        self.commandLinkButton_3.setText(_translate("CoordsConverterDialogBase", "UTM to DD"))
        self.commandLinkButton_4.setText(_translate("CoordsConverterDialogBase", "UTM to DMS"))
        self.commandLinkButton_5.setText(_translate("CoordsConverterDialogBase", "DMS to DD"))
        self.commandLinkButton_6.setText(_translate("CoordsConverterDialogBase", "DMS to UTM"))
